# MQ connection information -------------------------------
qmgrConnectionParams:
  # Queue manager name.
  qmgrName: QM
  # Queue manager host.
  qmgrHost: esmqsi2.pdc.aa.com
  # Queue manager connection port.
  qmgrPort: 1436
  # Queue manager connection channel.
  qmgrChannel: ESMQSI2.VPNG.02
  # Username, which will be used for connection (optional).
  # User must have permission to subscribe to the topic $SYS/MQ/INFO/QMGR/QM/Monitor/ and all subtopics.
  # User also must have permission to inquire  channels, queues and listeners listed below in Monitoring objects section!
  user: vpmqssi
  # Password, which will be used for connection (optional).
  password: ax7$uNv42573
  # Use MQCSP for connection?
  mqscp: false
  # How long to wait until metrics are published by queue manager (milliseconds).
  # Value must be at least 10000 (periodicity with which metrics are published by MQ).
  connTimeout: 12000
  # Use TLS connection to queue manager? If useTLS equals "false" than all connection parameters below will be ignored.
  useTLS: false
  # Path to keystore file
  keystorePath: /opt/mq_exporter/keystores/keystore.jks
  # Keystore password
  keystorePassword: testpass2
  # Path to truststore file
  truststorePath: /opt/mq_exporter/keystores/truststore.jks
  # Truststore password
  truststorePassword: testpass2
  # SSL protocol
  sslProtocol: TLSv1.2
  # CipherSuite
  cipherSuite: TLS_RSA_WITH_AES_256_CBC_SHA256

# Prometheus connection information -------------------------------
prometheusEndpointParams:
  # URL and port which will be used to expose metrics for Prometheus.
  url: /metrics
  port: 8080


# Monitoring objects ----------------------------------
# This block refers to collecting of additional metrics.
# If there are any queues, channels or listeners in the config file below,
# these metrics may be useful for you. (More info about additional metrics is located 
# under "MQ PCF API specific statistics" section.   
PCFParameters:
  # Collect additional metrics? If false, all settings in this section below are ignored.
  # If yes, additional metrics will be collected for all queues, channels and listeners listed below.
  sendPCFCommands: true
  # Interval in seconds between sending PCF commands.
  scrapeInterval: 30

# Further block contains info about monitoring objects. It supports "*" wildcard at the end of the name.
# Firstly, objects from "include" section are retrieved.
# Then objects from "exclude" section are retrieved.
# Objects that are in the first group but not in the second are added to the monitoring list

#Interval in seconds between updating objects (in case some objects were removed or created).
updateInterval: 30

# Monitored queues.
queues:
  include:
    - '*'
  exclude:
    - SYSTEM.*

# Monitored listeners.
listeners:
  include:
    - '*'
  exclude:
    - SYSTEM.*

# Monitored channels.
monitorAutoDefinedClusterChannels: true
channels:
  include:
    - '*'